on: 
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs: 
  azurestack-test:
    runs-on: self-hosted
    steps:

      - name: Login to AzureStack with Az Powershell.
        uses: azure/login@releases/v1
        with:
          creds: ${{ secrets.BELLEVUE_AAD_SP_SECRET }}
          environment: 'AzureStack'
          enable-AzPSSession: true

      - name: Test Az Powershell Commands.
        shell: pwsh
        run: |
          hostname
          Get-AzContext
          Get-AzResourceGroup

      - name: Checkout ${{ github.repository }}.
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Checkout Another Repository.
        uses: actions/checkout@v2
        with:
          repository: Azure-Samples/Hybrid-compute-nodejs-create-vm
          ref: master
          path: ${{ github.workspace }}\temp

      - name: Run Azure Stack SDK Samples.
        shell: pwsh
        env:
          BELLEVUE_AAD_SP_SECRET: ${{ secrets.BELLEVUE_AAD_SP_SECRET }}
        run: |
          ${{ github.workspace }}\tool\setup-environment.ps1
          ${{ github.workspace }}\run-sample.ps1
          ${{ github.workspace }}\tool\cleanup-environment.ps1
